### PR TITLE
missing software-properties-common & python3-distutils

### PR DESCRIPTION
**Pull request by WaaromZoMoeilijk**
https://github.com/FreeTAKTeam/FreeTAKHub-Installation/issues/18#issuecomment-1062738309

### CODE REVIEW

**Comment by jonaugustine** [comment]
currently failing tests

**Comment by WaaromZoMoeilijk** [comment]
I'll have a look later, finally got it working on a regular VM, will try the LXC container again later.

**Comment by jonaugustine** [comment]
I've added distutils but not software-properties-common, is it necessary?

**Comment by juneseptaugust** [comment]
OBE by #234

**Pull request closed without merging**
